const hackathonData = [
  {
    id: 1,
    title: 'Heart Monitoring System',
    organizer: 'Mic College of Technology',
    prize: '3000',
    participants: 2456,
    deadlineText: '14 Days Left',
    deadlineFull: 'May 26, 12:30pm , GMT +5:30',
    mode: 'online',
    type: 'Public',
    skills: ['Html', 'Css', 'Bootstrap'],
  },
  {
    id: 1,
    title: 'Heart Monitoring System',
    organizer: 'Mic College of Technology',
    prize: '3000',
    participants: 2456,
    deadlineText: '14 Days Left',
    deadlineFull: 'May 26, 12:30pm , GMT +5:30',
    mode: 'online',
    type: 'Public',
    skills: ['Html', 'Css', 'Bootstrap'],
  },
  {
    id: 2,
    title: 'AI in Action',
    organizer: 'Mic College of Technology',
    prize: '6000',
    participants: 2456,
    deadlineText: '2 Days Left',
    deadlineFull: 'May 26, 12:30pm , GMT +5:30',
    mode: 'online',
    type: 'Public',
    skills: ['Html', 'Css', 'Bootstrap'],
  },
  {
    id: 3,
    title: 'NVIDIA Developer Challenge',
    organizer: 'Mic College of Technology',
    prize: '4000',
    participants: 2456,
    deadlineText: '30 Days Left',
    deadlineFull: 'May 26, 12:30pm , GMT +5:30',
    mode: 'online',
    type: 'Public',
    skills: ['Html', 'Css', 'Bootstrap'],
  },
];

export default hackathonData;
