import {
  FaChalkboardTeacher,
  FaClipboardCheck,
  FaBook,
  FaHourglassHalf,
} from "react-icons/fa";
import SchoolIcon from "@mui/icons-material/School";
import AssignmentIcon from "@mui/icons-material/Assignment";
export const metricsCard1 = [
  {
    title: "Total enroll courses",
    value: 5,
    maxValue: 5,
    text: "5",
    icon: <SchoolIcon />,
    color: "#00C49F",
    bgColor: "#E0F7F4",
  },
  {
    title: "Course completed",
    value: 1,
    maxValue: 5,
    text: "1",
    icon: <AssignmentIcon />,
    color: "#00B0FF",
    bgColor: "#E0F3FF",
  },
  {
    title: "Hours spent",
    value: 112,
    text: "112h",
    icon: <FaHourglassHalf />,
    color: "#FF4081",
    bgColor: "#FFEAF2",
  },
];

export const metricsCard2 = [
  {
    title: "Live class attended",
    value: 70,
    maxValue: 100,
    text: "70%",
    icon: <FaChalkboardTeacher />,
    color: "#FF6D60",
    bgColor: "#FFE5E0",
  },
  {
    title: "Quiz practised",
    value: 20,
    maxValue: 30,
    text: "20/30",
    icon: <FaBook />,
    color: "#9C6ADE",
    bgColor: "#EFE4FD",
  },
  {
    title: "Assignment done",
    value: 10,
    maxValue: 15,
    text: "10/15",
    icon: <FaClipboardCheck />,
    color: "#4285F4",
    bgColor: "#E3EEFD",
  },
];
export const classList = [
  {
    title: "Newtonian Mechanics – Class 5",
    subject: "Physics 1",
    subjectColor: "#ef4444",
    teacher: "Rakesh Ahmed",
    image: "https://via.placeholder.com/64x64?text=📘",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "2 min left",
    timeColor: "#ef4444",
    liveDotColor: "#dc2626",
  },
  {
    title: "Polymer – Class 3",
    subject: "Chemistry 1",
    subjectColor: "#3b82f6",
    teacher: "Khalil Khan",
    image: "https://via.placeholder.com/64x64?text=🧪",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "4 hr left",
    timeColor: "#3b82f6",
    liveDotColor: "#2563eb",
  },
];
export const classList2 = [
  {
    title: "Newtonian Mechanics – Class 5",
    subject: "Physics 1",
    subjectColor: "#ef4444",
    teacher: "Rakesh Ahmed",
    image: "https://via.placeholder.com/64x64?text=📘",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "2 min left",
    timeColor: "#ef4444",
    liveDotColor: "#dc2626",
    status: "active",
  },
  {
    title: "Polymer – Class 3",
    subject: "Chemistry 1",
    subjectColor: "#3b82f6",
    teacher: "Khalil Khan",
    image: "https://via.placeholder.com/64x64?text=🧪",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "4 hr left",
    timeColor: "#3b82f6",
    liveDotColor: "#2563eb",
    status: "active",
  },
  {
    title: "Newtonian Mechanics – Class 5",
    subject: "Physics 1",
    subjectColor: "#ef4444",
    teacher: "Rakesh Ahmed",
    image: "https://via.placeholder.com/64x64?text=📘",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "2 min left",
    timeColor: "#ef4444",
    liveDotColor: "#dc2626",
    status: "inactive",
  },
  {
    title: "Polymer – Class 3",
    subject: "Chemistry 1",
    subjectColor: "#3b82f6",
    teacher: "Khalil Khan",
    image: "https://via.placeholder.com/64x64?text=🧪",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "4 hr left",
    timeColor: "#3b82f6",
    liveDotColor: "#2563eb",
    status: "active",
  },
  {
    title: "Newtonian Mechanics – Class 5",
    subject: "Physics 1",
    subjectColor: "#ef4444",
    teacher: "Rakesh Ahmed",
    image: "https://via.placeholder.com/64x64?text=📘",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "2 min left",
    timeColor: "#ef4444",
    liveDotColor: "#dc2626",
    status: "inactive",
  },
  {
    title: "Polymer – Class 3",
    subject: "Chemistry 1",
    subjectColor: "#3b82f6",
    teacher: "Khalil Khan",
    image: "https://via.placeholder.com/64x64?text=🧪",
    dateTime: "15th Oct, 2024 ; 12:00PM",
    timeLeft: "4 hr left",
    timeColor: "#3b82f6",
    liveDotColor: "#2563eb",
    status: "active",
  },
];
export const classList3 = [
  {
    id: 1,
    subject: "Physics 1",
    chapters: 5,
    lectures: 30,
    progress: 30,
    score: 80,
    status: "In progress",
    color: "#ff7043",
    avatar: "P",
  },
  {
    id: 2,
    subject: "Physics 2",
    chapters: 5,
    lectures: 30,
    progress: 30,
    score: 80,
    status: "In progress",
    color: "#ff7043",
    avatar: "P",
  },
  {
    id: 3,
    subject: "Chemistry 1",
    chapters: 5,
    lectures: 30,
    progress: 30,
    score: 70,
    status: "In progress",
    color: "#29b6f6",
    avatar: "C",
  },
  {
    id: 4,
    subject: "Chemistry 2",
    chapters: 5,
    lectures: 30,
    progress: 30,
    score: 80,
    status: "In progress",
    color: "#29b6f6",
    avatar: "C",
  },
  {
    id: 5,
    subject: "Higher math 1",
    chapters: 5,
    lectures: 30,
    progress: 100,
    score: 90,
    status: "Completed",
    color: "#7e57c2",
    avatar: "H",
  },
];
